<a href="https://colab.research.google.com/github/Vinayakmoudgil/MLOps/blob/main/Model_selection_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Model Selection for the Data set

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [14]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
y_svr=y.reshape(len(y),1)

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Splitting the dataset into the Training set and Test set for SVR

In [42]:
from sklearn.model_selection import train_test_split
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X, y_svr, test_size = 0.2, random_state = 0)

Feature scaling for SVR

In [43]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
scy=StandardScaler()
X_train_s=scx.fit_transform(X_train_s)
y_train_s=scy.fit_transform(y_train_s)

## Training the Regression models on the Training set

Mulitple Linear Regression Model

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)


LinearRegression()

Training Polynomial Regression Model

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
ply_reg=PolynomialFeatures(degree=4)
reg_poly=LinearRegression()
reg_poly.fit(ply_reg.fit_transform(X_train),y_train)

SVR Training the data set

In [45]:
from sklearn.svm import SVR
reg_svr=SVR(kernel='rbf')
reg_svr.fit(X_train_s,y_train_s)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Traing the Decision tree model

In [51]:
from sklearn.tree import DecisionTreeRegressor
reg_dt=DecisionTreeRegressor(random_state=0)
reg_dt.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

Training the Random Forest Model

In [60]:
from sklearn.ensemble import RandomForestRegressor
reg_rfm=RandomForestRegressor(n_estimators=10,random_state=0)
reg_rfm.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting the Test set results for all the Models




Predicting the result for Multiple Regression Model

In [11]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]
[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


Predicting result for Polynomial regression

In [58]:
y_pred_poly=reg_poly.predict(ply_reg.fit_transform(X_test))
print(np.concatenate((y_pred_poly.reshape(len(y_pred_poly),1),y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


Predicting SVR results

In [57]:
y_pred_svr=scy.inverse_transform([reg_svr.predict(scx.transform(X_test_s))]).reshape(-1,1)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_svr.reshape(-1,1),y_test.reshape(-1,1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


Predicting results for Decision tree Model

In [53]:
y_pred_dt=reg_dt.predict(X_test)
print(np.concatenate((y_pred.reshape(-1,1),y_test.reshape(-1,1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


Prediction for Random Forest Model

In [62]:
y_pred_rfm=reg_rfm.predict(X_test)
print(np.concatenate((y_pred_rfm.reshape(-1,1),y_test.reshape(-1,1)),1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


## Evaluating the Model Performance for all the Models

In [85]:
from sklearn.metrics import r2_score
all_pred={}
all_pred['Mutiple Regression Model']=(r2_score(y_test, y_pred))
all_pred['Polynomial Regression Model']=(r2_score(y_test,y_pred_poly))
all_pred['SVR Model']=(r2_score(y_test,y_pred_svr))
all_pred['Decision Tree Model']=(r2_score(y_test,y_pred_dt))
all_pred['Randoom Forest Model']=(r2_score(y_test,y_pred_rfm))
print(all_pred)
print('Model Slected: ',max(zip(all_pred.values(),all_pred.keys())))

{'Mutiple Regression Model': 0.9325315554761303, 'Polynomial Regression Model': 0.9458192606428147, 'SVR Model': 0.9480784049986258, 'Decision Tree Model': 0.922905874177941, 'Randoom Forest Model': 0.9615908334363876}
Model Slected:  (0.9615908334363876, 'Randoom Forest Model')
